import os

# screen constants
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# player constants
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.5
PLAYER_HEALTH = 500
PLAYER_SHOT_DMG = 50

# Skeleton constants
SKELETON_TURN_SPEED = 300
SKELETON_SPEED = 200
SKELETON_SHOOT_SPEED = 500
SKELETON_SHOOT_COOLDOWN = 0.7
SKELETON_HEALTH = 250
SKELETON_SHOT_DMG = 75

# SHOTS
SHOT_RADIUS = 5
LINE_WIDTH = 2
HIT_RADIUS = 10

# Map constants
MAP_WIDTH = 1280
MAP_HEIGHT = 720
WALL_THICKNESS = 30

# FILE SOURCES
BASE_PATH = os.path.dirname(__file__)
PLAYER_SPRITES = os.path.join(BASE_PATH, '..', 'sprites', 'mage')
SKELETON_SPRITES = os.path.join(BASE_PATH, '..', 'sprites', 'skeleton')
